// Both clients use src/mindmapCanvas.ts. Embed the self-contained phone bundle
// in a Python module so installed services need neither Node.js nor a CDN.
import { build } from 'vite';
import { writeFile, readFile, readdir } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
const result=await build({configFile:false,logLevel:'warn',build:{write:false,minify:true,lib:{entry:'src/mindmapCanvas.ts',name:'ShuyingMindmap',formats:['iife']}}});
const bundle=(Array.isArray(result)?result[0]:result).output.find(item=>item.type==='chunk').code;
const notices=[];
for(const entry of (await readdir('node_modules/.pnpm')).sort()){
  if(!/^(markmap-|d3[\-@]|internmap@|@babel\+runtime@|@gera2ld\+jsx-dom@|npm2url@|delaunator@|robust-predicates@)/.test(entry))continue;
  const name=entry.split('@').filter(Boolean)[0].replace('+','/');
  const packageName=entry.startsWith('@')?'@'+name:name;
  const dir=`node_modules/.pnpm/${entry}/node_modules/${packageName}`;
  for(const file of (await readdir(dir)).filter(name=>/^license/i.test(name))){notices.push(packageName+'\n'+await readFile(`${dir}/${file}`,'utf8'));}
}
const code='/* Third-party notices\n'+notices.join('\n\n').replaceAll('*/','* /')+'\n*/\n'+bundle;
const encoded=gzipSync(code,{level:9}).toString('base64');
await writeFile('backend/videosummarizer/mindmap_assets.py','# Generated by scripts/build_mindmap.mjs; do not edit.\nimport base64\nimport gzip\n\nJS = gzip.decompress(base64.b64decode(\n'+encoded.match(/.{1,100}/g).map(line=>'    "'+line+'"').join('\n')+'\n)).decode("utf-8")\n');
console.log(`Mind-map canvas bundled: ${Buffer.byteLength(code)} bytes, ${encoded.length} encoded bytes`);
